export enum StorageKeys {
  LAST_FOLDER = "AUDIOSERVE_LAST_FOLDER",
  LAST_COLLECTION = "AUDIOSERVE_LAST_COLLECTION",
  LAST_FILE = "AUDIOSERVE_LAST_FILE",
  LAST_POSITION = "AUDIOSERVE_LAST_POSITION",
  THEME = "AUDIOSERVE_THEME",
}

export enum FolderType {
  REGULAR,
  SEARCH,
  RECENT
}
