/* tslint:disable */
/* eslint-disable */
/**
 * audioserve API
 * REST API for audioserve
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AudioFileMeta
 */
export interface AudioFileMeta {
    /**
     * Duration of audio file in seconds
     * @type {number}
     * @memberof AudioFileMeta
     */
    duration?: number;
    /**
     * Encoding bitrate of file - original, before transcoding
     * @type {number}
     * @memberof AudioFileMeta
     */
    bitrate?: number;
    /**
     * Metadata tags as map of name to value
     * @type {object}
     * @memberof AudioFileMeta
     */
    tags?: object | null;
}

/**
 * Check if a given object implements the AudioFileMeta interface.
 */
export function instanceOfAudioFileMeta(value: object): value is AudioFileMeta {
    return true;
}

export function AudioFileMetaFromJSON(json: any): AudioFileMeta {
    return AudioFileMetaFromJSONTyped(json, false);
}

export function AudioFileMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioFileMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'] == null ? undefined : json['duration'],
        'bitrate': json['bitrate'] == null ? undefined : json['bitrate'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function AudioFileMetaToJSON(json: any): AudioFileMeta {
    return AudioFileMetaToJSONTyped(json, false);
}

export function AudioFileMetaToJSONTyped(value?: AudioFileMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration': value['duration'],
        'bitrate': value['bitrate'],
        'tags': value['tags'],
    };
}

