/* tslint:disable */
/* eslint-disable */
/**
 * audioserve API
 * REST API for audioserve
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SharedSecret
 */
export interface SharedSecret {
    /**
     * Salted shared secret
     * @type {string}
     * @memberof SharedSecret
     */
    secret: string;
}

/**
 * Check if a given object implements the SharedSecret interface.
 */
export function instanceOfSharedSecret(value: object): value is SharedSecret {
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function SharedSecretFromJSON(json: any): SharedSecret {
    return SharedSecretFromJSONTyped(json, false);
}

export function SharedSecretFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedSecret {
    if (json == null) {
        return json;
    }
    return {
        
        'secret': json['secret'],
    };
}

export function SharedSecretToJSON(json: any): SharedSecret {
    return SharedSecretToJSONTyped(json, false);
}

export function SharedSecretToJSONTyped(value?: SharedSecret | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'secret': value['secret'],
    };
}

