/* tslint:disable */
/* eslint-disable */
/**
 * audioserve API
 * REST API for audioserve
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Subfolder
 */
export interface Subfolder {
    /**
     * 
     * @type {string}
     * @memberof Subfolder
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Subfolder
     */
    path: string;
    /**
     * Is virtual folder - e.g. representing big chapterized file (.m4b etc.)
     * @type {boolean}
     * @memberof Subfolder
     */
    isFile?: boolean;
    /**
     * last modification timestamp (unix time in miliseconds)
     * @type {number}
     * @memberof Subfolder
     */
    modified?: number;
    /**
     * was folder listened to the end (by given group, valid only if group parameter was provided)
     * @type {boolean}
     * @memberof Subfolder
     */
    finished?: boolean;
}

/**
 * Check if a given object implements the Subfolder interface.
 */
export function instanceOfSubfolder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "path" in value;

    return isInstance;
}

export function SubfolderFromJSON(json: any): Subfolder {
    return SubfolderFromJSONTyped(json, false);
}

export function SubfolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subfolder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'path': json['path'],
        'isFile': !exists(json, 'is_file') ? undefined : json['is_file'],
        'modified': !exists(json, 'modified') ? undefined : json['modified'],
        'finished': !exists(json, 'finished') ? undefined : json['finished'],
    };
}

export function SubfolderToJSON(value?: Subfolder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'path': value.path,
        'is_file': value.isFile,
        'modified': value.modified,
        'finished': value.finished,
    };
}

