/* tslint:disable */
/* eslint-disable */
/**
 * audioserve API
 * REST API for audioserve
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transcoding } from './Transcoding';
import {
    TranscodingFromJSON,
    TranscodingFromJSONTyped,
    TranscodingToJSON,
    TranscodingToJSONTyped,
} from './Transcoding';

/**
 * 
 * @export
 * @interface TranscodingsInfo
 */
export interface TranscodingsInfo {
    /**
     * 
     * @type {Transcoding}
     * @memberof TranscodingsInfo
     */
    high?: Transcoding;
    /**
     * 
     * @type {Transcoding}
     * @memberof TranscodingsInfo
     */
    low?: Transcoding;
    /**
     * 
     * @type {Transcoding}
     * @memberof TranscodingsInfo
     */
    medium?: Transcoding;
    /**
     * Maximum number of parallel transcodings allowed by server
     * @type {number}
     * @memberof TranscodingsInfo
     */
    maxTranscodings?: number;
}

/**
 * Check if a given object implements the TranscodingsInfo interface.
 */
export function instanceOfTranscodingsInfo(value: object): value is TranscodingsInfo {
    return true;
}

export function TranscodingsInfoFromJSON(json: any): TranscodingsInfo {
    return TranscodingsInfoFromJSONTyped(json, false);
}

export function TranscodingsInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranscodingsInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'high': json['high'] == null ? undefined : TranscodingFromJSON(json['high']),
        'low': json['low'] == null ? undefined : TranscodingFromJSON(json['low']),
        'medium': json['medium'] == null ? undefined : TranscodingFromJSON(json['medium']),
        'maxTranscodings': json['max_transcodings'] == null ? undefined : json['max_transcodings'],
    };
}

export function TranscodingsInfoToJSON(json: any): TranscodingsInfo {
    return TranscodingsInfoToJSONTyped(json, false);
}

export function TranscodingsInfoToJSONTyped(value?: TranscodingsInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'high': TranscodingToJSON(value['high']),
        'low': TranscodingToJSON(value['low']),
        'medium': TranscodingToJSON(value['medium']),
        'max_transcodings': value['maxTranscodings'],
    };
}

