/* tslint:disable */
/* eslint-disable */
/**
 * audioserve API
 * REST API for audioserve
 *
 * The version of the OpenAPI document: 1.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Transcoding
 */
export interface Transcoding {
    /**
     * Name of transcoding in form of audio_codec-in-container, for instance opus-in-ogg
     * @type {string}
     * @memberof Transcoding
     */
    name: string;
    /**
     * Average bitrate of the transcoding in kbps
     * @type {number}
     * @memberof Transcoding
     */
    bitrate: number;
}

/**
 * Check if a given object implements the Transcoding interface.
 */
export function instanceOfTranscoding(value: object): value is Transcoding {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('bitrate' in value) || value['bitrate'] === undefined) return false;
    return true;
}

export function TranscodingFromJSON(json: any): Transcoding {
    return TranscodingFromJSONTyped(json, false);
}

export function TranscodingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transcoding {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'bitrate': json['bitrate'],
    };
}

export function TranscodingToJSON(json: any): Transcoding {
    return TranscodingToJSONTyped(json, false);
}

export function TranscodingToJSONTyped(value?: Transcoding | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'bitrate': value['bitrate'],
    };
}

