/* tslint:disable */
/* eslint-disable */
/**
 * audioserve API
 * REST API for audioserve
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Transcoding
 */
export interface Transcoding {
    /**
     * Name of transcoding in form of audio_codec-in-container, for instance opus-in-ogg
     * @type {string}
     * @memberof Transcoding
     */
    name: string;
    /**
     * Average bitrate of the transcoding in kbps
     * @type {number}
     * @memberof Transcoding
     */
    bitrate: number;
}

/**
 * Check if a given object implements the Transcoding interface.
 */
export function instanceOfTranscoding(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "bitrate" in value;

    return isInstance;
}

export function TranscodingFromJSON(json: any): Transcoding {
    return TranscodingFromJSONTyped(json, false);
}

export function TranscodingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transcoding {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'bitrate': json['bitrate'],
    };
}

export function TranscodingToJSON(value?: Transcoding | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'bitrate': value.bitrate,
    };
}

