/* tslint:disable */
/* eslint-disable */
/**
 * audioserve API
 * REST API for audioserve
 *
 * The version of the OpenAPI document: 1.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypedFile
 */
export interface TypedFile {
    /**
     * path to the file with collection
     * @type {string}
     * @memberof TypedFile
     */
    path: string;
    /**
     * mime type of the file
     * @type {string}
     * @memberof TypedFile
     */
    mime: string;
}

/**
 * Check if a given object implements the TypedFile interface.
 */
export function instanceOfTypedFile(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "path" in value;
    isInstance = isInstance && "mime" in value;

    return isInstance;
}

export function TypedFileFromJSON(json: any): TypedFile {
    return TypedFileFromJSONTyped(json, false);
}

export function TypedFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedFile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'path': json['path'],
        'mime': json['mime'],
    };
}

export function TypedFileToJSON(value?: TypedFile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'path': value.path,
        'mime': value.mime,
    };
}

