name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Build
        run: |
          npm install
          npm run build-sw
          npm run build
          npm test
      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: dist
          retention-days: 5
